package br.com.agendacorba.agenda.backbone;


/**
* br/com/agendacorba/agenda/backbone/_AgendaBackboneStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Monday, September 19, 2016 11:31:05 PM BRT
*/

public class _AgendaBackboneStub extends org.omg.CORBA.portable.ObjectImpl implements br.com.agendacorba.agenda.backbone.AgendaBackbone
{

  public void propagateCreate (br.com.agendacorba.agenda.Contact newContact)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("propagateCreate", true);
                br.com.agendacorba.agenda.ContactHelper.write ($out, newContact);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                propagateCreate (newContact        );
            } finally {
                _releaseReply ($in);
            }
  } // propagateCreate

  public br.com.agendacorba.agenda.Contact[] getAll ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getAll", true);
                $in = _invoke ($out);
                br.com.agendacorba.agenda.Contact $result[] = br.com.agendacorba.agenda.contactListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getAll (        );
            } finally {
                _releaseReply ($in);
            }
  } // getAll

  public void propagateUpdate (br.com.agendacorba.agenda.Contact updatedContact)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("propagateUpdate", true);
                br.com.agendacorba.agenda.ContactHelper.write ($out, updatedContact);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                propagateUpdate (updatedContact        );
            } finally {
                _releaseReply ($in);
            }
  } // propagateUpdate

  public void propagateDelete (br.com.agendacorba.agenda.Contact deletedContact)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("propagateDelete", true);
                br.com.agendacorba.agenda.ContactHelper.write ($out, deletedContact);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                propagateDelete (deletedContact        );
            } finally {
                _releaseReply ($in);
            }
  } // propagateDelete

  public void bindDuplexConnection (String requesterName)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("bindDuplexConnection", true);
                $out.write_string (requesterName);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                bindDuplexConnection (requesterName        );
            } finally {
                _releaseReply ($in);
            }
  } // bindDuplexConnection

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br/com/agendacorba/agenda/backbone/AgendaBackbone:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _AgendaBackboneStub
