package br.com.agendacorba.agenda.backbone;

/**
* br/com/agendacorba/agenda/backbone/AgendaBackboneHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Tuesday, September 20, 2016 10:59:36 PM BRT
*/

public final class AgendaBackboneHolder implements org.omg.CORBA.portable.Streamable
{
  public br.com.agendacorba.agenda.backbone.AgendaBackbone value = null;

  public AgendaBackboneHolder ()
  {
  }

  public AgendaBackboneHolder (br.com.agendacorba.agenda.backbone.AgendaBackbone initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.com.agendacorba.agenda.backbone.AgendaBackboneHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.com.agendacorba.agenda.backbone.AgendaBackboneHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.com.agendacorba.agenda.backbone.AgendaBackboneHelper.type ();
  }

}
