package br.com.agendacorba.agenda.backbone;


/**
* br/com/agendacorba/agenda/backbone/AgendaBackboneHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Tuesday, September 20, 2016 1:17:59 AM BRT
*/

abstract public class AgendaBackboneHelper
{
  private static String  _id = "IDL:br/com/agendacorba/agenda/backbone/AgendaBackbone:1.0";

  public static void insert (org.omg.CORBA.Any a, br.com.agendacorba.agenda.backbone.AgendaBackbone that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static br.com.agendacorba.agenda.backbone.AgendaBackbone extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (br.com.agendacorba.agenda.backbone.AgendaBackboneHelper.id (), "AgendaBackbone");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static br.com.agendacorba.agenda.backbone.AgendaBackbone read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AgendaBackboneStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, br.com.agendacorba.agenda.backbone.AgendaBackbone value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static br.com.agendacorba.agenda.backbone.AgendaBackbone narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof br.com.agendacorba.agenda.backbone.AgendaBackbone)
      return (br.com.agendacorba.agenda.backbone.AgendaBackbone)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      br.com.agendacorba.agenda.backbone._AgendaBackboneStub stub = new br.com.agendacorba.agenda.backbone._AgendaBackboneStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static br.com.agendacorba.agenda.backbone.AgendaBackbone unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof br.com.agendacorba.agenda.backbone.AgendaBackbone)
      return (br.com.agendacorba.agenda.backbone.AgendaBackbone)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      br.com.agendacorba.agenda.backbone._AgendaBackboneStub stub = new br.com.agendacorba.agenda.backbone._AgendaBackboneStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
