package br.com.agendacorba.agenda.backbone;


/**
* br/com/agendacorba/agenda/backbone/AgendaBackbone.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Monday, September 19, 2016 11:31:05 PM BRT
*/

public interface AgendaBackbone extends AgendaBackboneOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AgendaBackbone
