package br.com.agendacorba.agenda;


/**
* br/com/agendacorba/agenda/ContactAlreadyExistsException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Monday, September 19, 2016 11:31:05 PM BRT
*/

public final class ContactAlreadyExistsException extends org.omg.CORBA.UserException
{
  public String message = null;
  public String name = null;

  public ContactAlreadyExistsException ()
  {
    super(ContactAlreadyExistsExceptionHelper.id());
  } // ctor

  public ContactAlreadyExistsException (String _message, String _name)
  {
    super(ContactAlreadyExistsExceptionHelper.id());
    message = _message;
    name = _name;
  } // ctor


  public ContactAlreadyExistsException (String $reason, String _message, String _name)
  {
    super(ContactAlreadyExistsExceptionHelper.id() + "  " + $reason);
    message = _message;
    name = _name;
  } // ctor

} // class ContactAlreadyExistsException
