package br.com.agendacorba.agenda;


/**
* br/com/agendacorba/agenda/contactListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Monday, September 19, 2016 11:31:05 PM BRT
*/


//especifica tipo pra passagem de lista
abstract public class contactListHelper
{
  private static String  _id = "IDL:br/com/agendacorba/agenda/contactList:1.0";

  public static void insert (org.omg.CORBA.Any a, br.com.agendacorba.agenda.Contact[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static br.com.agendacorba.agenda.Contact[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = br.com.agendacorba.agenda.ContactHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (br.com.agendacorba.agenda.contactListHelper.id (), "contactList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static br.com.agendacorba.agenda.Contact[] read (org.omg.CORBA.portable.InputStream istream)
  {
    br.com.agendacorba.agenda.Contact value[] = null;
    int _len0 = istream.read_long ();
    value = new br.com.agendacorba.agenda.Contact[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = br.com.agendacorba.agenda.ContactHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, br.com.agendacorba.agenda.Contact[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      br.com.agendacorba.agenda.ContactHelper.write (ostream, value[_i0]);
  }

}
