package br.com.agendacorba.agenda;


/**
* br/com/agendacorba/agenda/ContactListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Tuesday, September 20, 2016 10:59:36 PM BRT
*/


//especifica tipo pra passagem de lista
public final class ContactListHolder implements org.omg.CORBA.portable.Streamable
{
  public br.com.agendacorba.agenda.Contact value[] = null;

  public ContactListHolder ()
  {
  }

  public ContactListHolder (br.com.agendacorba.agenda.Contact[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.com.agendacorba.agenda.ContactListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.com.agendacorba.agenda.ContactListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.com.agendacorba.agenda.ContactListHelper.type ();
  }

}
