package br.com.agendacorba.agenda;

/**
* br/com/agendacorba/agenda/ContactAlreadyExistsExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Tuesday, September 20, 2016 10:59:36 PM BRT
*/

public final class ContactAlreadyExistsExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public br.com.agendacorba.agenda.ContactAlreadyExistsException value = null;

  public ContactAlreadyExistsExceptionHolder ()
  {
  }

  public ContactAlreadyExistsExceptionHolder (br.com.agendacorba.agenda.ContactAlreadyExistsException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.com.agendacorba.agenda.ContactAlreadyExistsExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.com.agendacorba.agenda.ContactAlreadyExistsExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.com.agendacorba.agenda.ContactAlreadyExistsExceptionHelper.type ();
  }

}
