package br.com.agendacorba.agenda;


/**
* br/com/agendacorba/agenda/MalformedTelNumberException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Tuesday, September 20, 2016 10:59:36 PM BRT
*/

public final class MalformedTelNumberException extends org.omg.CORBA.UserException
{

  public MalformedTelNumberException ()
  {
    super(MalformedTelNumberExceptionHelper.id());
  } // ctor


  public MalformedTelNumberException (String $reason)
  {
    super(MalformedTelNumberExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class MalformedTelNumberException
