package br.com.agendacorba.agenda;


/**
* br/com/agendacorba/agenda/MalformedTelNumberException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Monday, September 19, 2016 11:31:05 PM BRT
*/

public final class MalformedTelNumberException extends org.omg.CORBA.UserException
{
  public String telNumber = null;

  public MalformedTelNumberException ()
  {
    super(MalformedTelNumberExceptionHelper.id());
  } // ctor

  public MalformedTelNumberException (String _telNumber)
  {
    super(MalformedTelNumberExceptionHelper.id());
    telNumber = _telNumber;
  } // ctor


  public MalformedTelNumberException (String $reason, String _telNumber)
  {
    super(MalformedTelNumberExceptionHelper.id() + "  " + $reason);
    telNumber = _telNumber;
  } // ctor

} // class MalformedTelNumberException
