package br.com.agendacorba.agenda;


/**
* br/com/agendacorba/agenda/NoContactFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Monday, September 19, 2016 11:31:05 PM BRT
*/

public final class NoContactFoundException extends org.omg.CORBA.UserException
{
  public String message = null;

  public NoContactFoundException ()
  {
    super(NoContactFoundExceptionHelper.id());
  } // ctor

  public NoContactFoundException (String _message)
  {
    super(NoContactFoundExceptionHelper.id());
    message = _message;
  } // ctor


  public NoContactFoundException (String $reason, String _message)
  {
    super(NoContactFoundExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class NoContactFoundException
