package br.com.agendacorba.agenda;


/**
* br/com/agendacorba/agenda/NoContactFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Tuesday, September 20, 2016 1:17:59 AM BRT
*/

public final class NoContactFoundException extends org.omg.CORBA.UserException
{

  public NoContactFoundException ()
  {
    super(NoContactFoundExceptionHelper.id());
  } // ctor


  public NoContactFoundException (String $reason)
  {
    super(NoContactFoundExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class NoContactFoundException
