package br.com.agendacorba.agenda;

/**
* br/com/agendacorba/agenda/NoContactFoundExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Tuesday, September 20, 2016 10:59:36 PM BRT
*/

public final class NoContactFoundExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public br.com.agendacorba.agenda.NoContactFoundException value = null;

  public NoContactFoundExceptionHolder ()
  {
  }

  public NoContactFoundExceptionHolder (br.com.agendacorba.agenda.NoContactFoundException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.com.agendacorba.agenda.NoContactFoundExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.com.agendacorba.agenda.NoContactFoundExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.com.agendacorba.agenda.NoContactFoundExceptionHelper.type ();
  }

}
