package br.com.agendacorba.agenda.access;


/**
* br/com/agendacorba/agenda/access/_AgendaAccessStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Tuesday, September 20, 2016 10:59:36 PM BRT
*/

public class _AgendaAccessStub extends org.omg.CORBA.portable.ObjectImpl implements br.com.agendacorba.agenda.access.AgendaAccess
{

  public void create (br.com.agendacorba.agenda.Contact created) throws br.com.agendacorba.agenda.ContactAlreadyExistsException, br.com.agendacorba.agenda.MalformedTelNumberException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("create", true);
                br.com.agendacorba.agenda.ContactHelper.write ($out, created);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/com/agendacorba/agenda/ContactAlreadyExistsException:1.0"))
                    throw br.com.agendacorba.agenda.ContactAlreadyExistsExceptionHelper.read ($in);
                else if (_id.equals ("IDL:br/com/agendacorba/agenda/MalformedTelNumberException:1.0"))
                    throw br.com.agendacorba.agenda.MalformedTelNumberExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                create (created        );
            } finally {
                _releaseReply ($in);
            }
  } // create

  public br.com.agendacorba.agenda.Contact getByName (String name) throws br.com.agendacorba.agenda.NoContactFoundException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getByName", true);
                $out.write_string (name);
                $in = _invoke ($out);
                br.com.agendacorba.agenda.Contact $result = br.com.agendacorba.agenda.ContactHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/com/agendacorba/agenda/NoContactFoundException:1.0"))
                    throw br.com.agendacorba.agenda.NoContactFoundExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getByName (name        );
            } finally {
                _releaseReply ($in);
            }
  } // getByName

  public br.com.agendacorba.agenda.Contact[] getAll () throws br.com.agendacorba.agenda.NoContactFoundException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getAll", true);
                $in = _invoke ($out);
                br.com.agendacorba.agenda.Contact $result[] = br.com.agendacorba.agenda.ContactListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/com/agendacorba/agenda/NoContactFoundException:1.0"))
                    throw br.com.agendacorba.agenda.NoContactFoundExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getAll (        );
            } finally {
                _releaseReply ($in);
            }
  } // getAll

  public void update (br.com.agendacorba.agenda.Contact contact) throws br.com.agendacorba.agenda.NoContactFoundException, br.com.agendacorba.agenda.MalformedTelNumberException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("update", true);
                br.com.agendacorba.agenda.ContactHelper.write ($out, contact);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/com/agendacorba/agenda/NoContactFoundException:1.0"))
                    throw br.com.agendacorba.agenda.NoContactFoundExceptionHelper.read ($in);
                else if (_id.equals ("IDL:br/com/agendacorba/agenda/MalformedTelNumberException:1.0"))
                    throw br.com.agendacorba.agenda.MalformedTelNumberExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                update (contact        );
            } finally {
                _releaseReply ($in);
            }
  } // update

  public void deleteByName (String name) throws br.com.agendacorba.agenda.NoContactFoundException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("propagateDelete", true);
                $out.write_string (name);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/com/agendacorba/agenda/NoContactFoundException:1.0"))
                    throw br.com.agendacorba.agenda.NoContactFoundExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                deleteByName (name        );
            } finally {
                _releaseReply ($in);
            }
  } // propagateDelete

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br/com/agendacorba/agenda/access/AgendaAccess:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _AgendaAccessStub
