package br.com.agendacorba.agenda.access;

/**
* br/com/agendacorba/agenda/access/AgendaAccessHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Monday, September 19, 2016 11:31:05 PM BRT
*/

public final class AgendaAccessHolder implements org.omg.CORBA.portable.Streamable
{
  public br.com.agendacorba.agenda.access.AgendaAccess value = null;

  public AgendaAccessHolder ()
  {
  }

  public AgendaAccessHolder (br.com.agendacorba.agenda.access.AgendaAccess initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.com.agendacorba.agenda.access.AgendaAccessHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.com.agendacorba.agenda.access.AgendaAccessHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.com.agendacorba.agenda.access.AgendaAccessHelper.type ();
  }

}
