package br.com.agendacorba.agenda.access;


/**
* br/com/agendacorba/agenda/access/AgendaAccess.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Tuesday, September 20, 2016 1:17:59 AM BRT
*/

public interface AgendaAccess extends AgendaAccessOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AgendaAccess
