package br.com.agendacorba.agenda.access;


/**
* br/com/agendacorba/agenda/access/AgendaAccess.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Monday, September 19, 2016 11:31:05 PM BRT
*/

public interface AgendaAccess extends AgendaAccessOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AgendaAccess
