package br.com.agendacorba.agenda.access;


/**
* br/com/agendacorba/agenda/access/AgendaAccessOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Tuesday, September 20, 2016 10:59:36 PM BRT
*/

public interface AgendaAccessOperations 
{
  void create (br.com.agendacorba.agenda.Contact created) throws br.com.agendacorba.agenda.ContactAlreadyExistsException, br.com.agendacorba.agenda.MalformedTelNumberException;
  br.com.agendacorba.agenda.Contact getByName (String name) throws br.com.agendacorba.agenda.NoContactFoundException;
  br.com.agendacorba.agenda.Contact[] getAll () throws br.com.agendacorba.agenda.NoContactFoundException;
  void update (br.com.agendacorba.agenda.Contact contact) throws br.com.agendacorba.agenda.NoContactFoundException, br.com.agendacorba.agenda.MalformedTelNumberException;
  void deleteByName (String name) throws br.com.agendacorba.agenda.NoContactFoundException;
} // interface AgendaAccessOperations
