package Matematica;


/**
* Matematica/Calculadora.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalcIDL.idl
* Tuesday, September 13, 2016 8:08:15 PM BRT
*/

public interface Calculadora extends CalculadoraOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculadora
