package Matematica;


/**
* Matematica/CalculadoraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalcIDL.idl
* Tuesday, September 13, 2016 8:08:15 PM BRT
*/

public interface CalculadoraOperations 
{
  float soma (float arg1, float arg2);
  float divisao (float arg1, float arg2) throws Matematica.DivisaoPorZero;
} // interface CalculadoraOperations
