package Matematica;


/**
* Matematica/DivisaoPorZero.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalcIDL.idl
* Tuesday, September 13, 2016 8:08:15 PM BRT
*/

public final class DivisaoPorZero extends org.omg.CORBA.UserException
{
  public float arg1 = (float)0;
  public float arg2 = (float)0;

  public DivisaoPorZero ()
  {
    super(DivisaoPorZeroHelper.id());
  } // ctor

  public DivisaoPorZero (float _arg1, float _arg2)
  {
    super(DivisaoPorZeroHelper.id());
    arg1 = _arg1;
    arg2 = _arg2;
  } // ctor


  public DivisaoPorZero (String $reason, float _arg1, float _arg2)
  {
    super(DivisaoPorZeroHelper.id() + "  " + $reason);
    arg1 = _arg1;
    arg2 = _arg2;
  } // ctor

} // class DivisaoPorZero
