package Matematica;


/**
* Matematica/DivisaoPorZeroHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalcIDL.idl
* Tuesday, September 13, 2016 8:08:15 PM BRT
*/

abstract public class DivisaoPorZeroHelper
{
  private static String  _id = "IDL:Matematica/DivisaoPorZero:1.0";

  public static void insert (org.omg.CORBA.Any a, Matematica.DivisaoPorZero that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Matematica.DivisaoPorZero extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[0] = new org.omg.CORBA.StructMember (
            "arg1",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[1] = new org.omg.CORBA.StructMember (
            "arg2",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (Matematica.DivisaoPorZeroHelper.id (), "DivisaoPorZero", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Matematica.DivisaoPorZero read (org.omg.CORBA.portable.InputStream istream)
  {
    Matematica.DivisaoPorZero value = new Matematica.DivisaoPorZero ();
    // read and discard the repository ID
    istream.read_string ();
    value.arg1 = istream.read_float ();
    value.arg2 = istream.read_float ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Matematica.DivisaoPorZero value)
  {
    // write the repository ID
    ostream.write_string (id ());
    ostream.write_float (value.arg1);
    ostream.write_float (value.arg2);
  }

}
